"""add briefs cache table

Revision ID: 9f4a945435fd
Revises: 842d47dd7acc
Create Date: 2026-07-25 16:52:26.784535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4a945435fd'
down_revision: Union[str, Sequence[str], None] = '842d47dd7acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('addressed', sa.Boolean(), nullable=False),
    sa.Column('quotes', sa.Text(), nullable=False),
    sa.Column('grounding_rate', sa.Float(), nullable=True),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'question', name='uq_company_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('briefs')
    # ### end Alembic commands ###
