"""add cash and investments to financials

Revision ID: a6123a77f155
Revises: 9f4a945435fd
Create Date: 2026-07-27 12:40:06.628625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6123a77f155'
down_revision: Union[str, Sequence[str], None] = '9f4a945435fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financials', sa.Column('cash', sa.Numeric(), nullable=True))
    op.add_column('financials', sa.Column('short_term_investments', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financials', 'short_term_investments')
    op.drop_column('financials', 'cash')
    # ### end Alembic commands ###
